//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrioHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUJETARC
    {
        public int Id { get; set; }
        public Nullable<byte> CRITERE1 { get; set; }
        public Nullable<byte> CRITERE2 { get; set; }
        public Nullable<byte> CRITERE3 { get; set; }
    }
}
